import {
  UserIcon,
  ComponentIcon,
  PreviewIcon,
  Icons,
  MenuIcon,
  XIcon,
  SidebarOpenIcon,
  SidebarCloseIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  PersonIcon,
  DownloadIcon,
  LoadIcon,
  TrashIcon,
  SearchIcon,
  ErrorIcon,
  WarningIcon,
  InfoIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  PasswordIcon,
  EyeOpenIcon,
  EyeClosedIcon,
  DragDropIcon,
  SidebarIncreaseLine,
  SidebarDecreaseLine,
} from "@/dev/icon/icon";

export const iconList = [
  { name: "ArrowLeftIcon", component: ArrowLeftIcon, category: "arrows" },
  { name: "ArrowRightIcon", component: ArrowRightIcon, category: "arrows" },
  { name: "ChevronUpIcon", component: ChevronUpIcon, category: "arrows" },
  { name: "ChevronDownIcon", component: ChevronDownIcon, category: "arrows" },
  { name: "ChevronLeftIcon", component: ChevronLeftIcon, category: "arrows" },
  { name: "ChevronRightIcon", component: ChevronRightIcon, category: "arrows" },
  { name: "SidebarOpenIcon", component: SidebarOpenIcon, category: "arrows" },
  { name: "SidebarCloseIcon", component: SidebarCloseIcon, category: "arrows" },

  { name: "UserIcon", component: UserIcon, category: "user" },
  { name: "PersonIcon", component: PersonIcon, category: "user" },
  { name: "PasswordIcon", component: PasswordIcon, category: "user" },
  { name: "EyeOpenIcon", component: EyeOpenIcon, category: "user" },
  { name: "EyeClosedIcon", component: EyeClosedIcon, category: "user" },

  { name: "TrashIcon", component: TrashIcon, category: "actions" },
  { name: "DownloadIcon", component: DownloadIcon, category: "actions" },
  { name: "SearchIcon", component: SearchIcon, category: "actions" },
  { name: "XIcon", component: XIcon, category: "actions" },
  { name: "MenuIcon", component: MenuIcon, category: "actions" },
  { name: "DragDropIcon", component: DragDropIcon, category: "actions" },

  { name: "ErrorIcon", component: ErrorIcon, category: "status" },
  { name: "WarningIcon", component: WarningIcon, category: "status" },
  { name: "InfoIcon", component: InfoIcon, category: "status" },
  { name: "LoadIcon", component: LoadIcon, category: "status" },

  { name: "ComponentIcon", component: ComponentIcon, category: "layout" },
  { name: "PreviewIcon", component: PreviewIcon, category: "layout" },
  { name: "Icons", component: Icons, category: "layout" },
  { name: "SidebarIncreaseLine", component: SidebarIncreaseLine, category: "layout" },
  { name: "SidebarDecreaseLine", component: SidebarDecreaseLine, category: "layout" },
];